# Default values for cosmonaut
replicaCount: 1

controlPlane:
  image:
    repository: cosmonaut/control-plane
    tag: latest
  port: 8080

ui:
  image:
    repository: cosmonaut/ui
    tag: latest
  port: 3000

plugins:
  trino:
    enabled: true
  spark:
    enabled: true
  flink:
    enabled: true
  airflow:
    enabled: true
  polaris:
    enabled: true
  kafka:
    enabled: true

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: cosmonaut.local
      paths:
        - path: /
          pathType: Prefix
