// Code generated by controller-gen. DO NOT EDIT.
// Run `make generate` to regenerate this file.

package registry

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of CosmoComponent into another instance.
func (in *CosmoComponent) DeepCopyInto(out *CosmoComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of CosmoComponent.
func (in *CosmoComponent) DeepCopy() *CosmoComponent {
	if in == nil {
		return nil
	}
	out := new(CosmoComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CosmoComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of CosmoComponentList into another instance.
func (in *CosmoComponentList) DeepCopyInto(out *CosmoComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CosmoComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CosmoComponentList.
func (in *CosmoComponentList) DeepCopy() *CosmoComponentList {
	if in == nil {
		return nil
	}
	out := new(CosmoComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CosmoComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of CosmoComponentSpec into another instance.
func (in *CosmoComponentSpec) DeepCopyInto(out *CosmoComponentSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of CosmoComponentSpec.
func (in *CosmoComponentSpec) DeepCopy() *CosmoComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CosmoComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of CosmoComponentStatus into another instance.
func (in *CosmoComponentStatus) DeepCopyInto(out *CosmoComponentStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CosmoComponentStatus.
func (in *CosmoComponentStatus) DeepCopy() *CosmoComponentStatus {
	if in == nil {
		return nil
	}
	out := new(CosmoComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of AuthSpec into another instance.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy returns a deep copy of AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}
