apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmonaut.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmonaut.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.driver "cockroachdb" }}
  {{- if .Values.cockroachdb.enabled }}
  host: {{ .Values.database.host | b64enc }}
  port: {{ .Values.database.port | toString | b64enc }}
  user: {{ .Values.database.user | b64enc }}
  password: {{ .Values.cockroachdb.password | default "" | b64enc }}
  {{- end }}
  {{- else if eq .Values.database.driver "postgres" }}
  host: {{ .Values.postgres.host | b64enc }}
  port: {{ .Values.postgres.port | toString | b64enc }}
  user: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  {{- else if eq .Values.database.driver "aurora" }}
  host: {{ .Values.aurora.host | b64enc }}
  port: {{ .Values.aurora.port | toString | b64enc }}
  user: {{ .Values.aurora.user | b64enc }}
  password: {{ .Values.aurora.password | b64enc }}
  region: {{ .Values.aurora.region | b64enc }}
  {{- else if eq .Values.database.driver "cloudsql" }}
  host: {{ .Values.cloudsql.host | b64enc }}
  port: {{ .Values.cloudsql.port | toString | b64enc }}
  user: {{ .Values.cloudsql.user | b64enc }}
  password: {{ .Values.cloudsql.password | b64enc }}
  instanceConnectionName: {{ .Values.cloudsql.instanceConnectionName | b64enc }}
  {{- else if eq .Values.database.driver "azure" }}
  host: {{ .Values.azure.host | b64enc }}
  port: {{ .Values.azure.port | toString | b64enc }}
  user: {{ .Values.azure.user | b64enc }}
  password: {{ .Values.azure.password | b64enc }}
  {{- end }}
  database: {{ .Values.database.database | b64enc }}
  sslMode: {{ .Values.database.sslMode | b64enc }}