apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmonaut.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmonaut.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cosmonaut.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: 8080
      targetPort: api
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
